/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package easymock;

import javax.annotation.Nonnull;

public class App {
    @Nonnull
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
