/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package easymock;

import org.easymock.EasyMock;
import org.junit.jupiter.api.Test;

import javax.swing.*;

class AppTest {
    @Test
    void partiallyMockedSwingComponent() {
        var mock = EasyMock.partialMockBuilder(JTable.class)
                .createMock();
    }

    @Test
    void partiallyMockedSwingComponentWithConstructor() {
        var mock = EasyMock.partialMockBuilder(JTable.class)
                .withConstructor()
                .createMock();
    }
}
